# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto

require 'google/protobuf'


descriptor_data = "\n\ntest.proto\x12\rcel.ruby.test\"\"\n\nTestStruct\x12\t\n\x01\x61\x18\x01 \x01(\x03\x12\t\n\x01\x62\x18\x02 \x01(\x03\x62\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Cel
  module Ruby
    module Test
      TestStruct = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cel.ruby.test.TestStruct").msgclass
    end
  end
end
