#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.5.1
# from Racc grammar file "".
#

require 'racc/parser.rb'

require 'strscan'
require 'bigdecimal'
module Cel
  class Parser < Racc::Parser

module_eval(<<'...end parser.ry/module_eval...', 'parser.ry', 24)

RESERVED = %W[
 in
as break const continue else
for function if import let
loop package namespace return
var void while
]

RESERVED_REGEX = Regexp.union(*RESERVED)

STRING_LIT_REGEX = Regexp.union(
  /"""(?~""")*"""/,
  /'''(?~''')*'''/,
  /"(\"|[^"])*"/,
  /'(\'|[^'])*'/,
)

NUMBER_REGEX = Regexp.union(
  /(0x[0-9a-fA-F]+)[uU]?/, # hexadecimal
  /(\d+)[uU]/, # uinteger
  /((\d*\.\d+)|\d+)([eE][+\-]?\d+)?/, # integer, float, exponent
)

def parse(str)
  tokenize(str)
  do_parse
end

def tokenize(str)
  str.force_encoding(Encoding::BINARY) unless str.valid_encoding?

  scanner = StringScanner.new(str)

  @q = []

  until scanner.eos?
    case
    when scanner.scan(/\s+/)
      # skip whitespace
    when scanner.scan(/#(( *)|( ?(?<string>.*)))\n/)
      # skip comment lines
    when scanner.scan(/\-?#{NUMBER_REGEX}/)
      @q << [:tNUMBER, convert_to_number(scanner)]
    when scanner.scan(/true|false/)
      @q << [:tBOOL, scanner.matched == "true"]
    when scanner.scan(/null/)
      @q << [:tNULL]
    when scanner.scan(/[bB]?[rR]?#{STRING_LIT_REGEX}/) # string
      # s = scanner.matched.yield_self {|s| s[1, s.length - 2] }
      #                  .gsub(DBL_QUOTE_STR_ESCAPE_SEQUENCES_RE) do |match|
      #                    case match
      #                    when '\\a' then "\a"
      #                    when '\\b' then "\b"
      #                    when '\\e' then "\e"
      #                    when '\\f' then "\f"
      #                    when '\\n' then "\n"
      #                    when '\\r' then "\r"
      #                    when '\\s' then "\s"
      #                    when '\\t' then "\t"
      #                    when '\\v' then "\v"
      #                    when '\\"' then '"'
      #                    end
      #                  end

      # s = scanner.matched.yield_self {|s| s[1, s.length - 2] }.gsub(/\\'/, "'")

      @q << [:tSTRING, convert_to_string(scanner.matched)]
    when scanner.scan(RESERVED_REGEX)
      @q << [:tRESERVED, scanner.matched]
    when scanner.scan(/[a-zA-Z][_a-zA-Z0-9]*/)
      @q << [:tIDENTIFIER, scanner.matched]
    when scanner.scan(/\A.|\n/o)
      s = scanner.matched
      @q << [s, s]
    else
      puts "fuckness"
    end
  end
  @q << [false, '$end']
end

def next_token
  @q.shift
end

def convert_to_number(scanner)
  matched = scanner.matched
  _, number, floating, exp = scanner.captures
  if !exp.empty?
    # third matched group, can only be a floating exponential, let's convert tout suite
    BigDecimal(matched)
  elsif !floating.empty?
    if number == floating || floating.start_with?(".")
      Float(matched)
    else
      BigDecimal(matched)
    end
  else
    if matched[-1].downcase == "u"
      Integer(matched[0..-2]).abs
    else
      Integer(matched)
    end
  end
end

TRIPE_DOUBLE_QUOTES = %Q{"""}
TRIPE_SINGLE_QUOTES = %Q{'''}

def convert_to_string(str)
  return convert_to_bytes(str.byteslice(2..-2)) if str.start_with?("b")

  if str.start_with?("r")
    # If preceded by an r or R character, the string is a raw string
    # and does not interpret escape sequences.
    str = str.byteslice(2..-2).inspect.byteslice(1..-2)
    return str
  end

  if str.size > 6 && (
    (str.start_with?(TRIPE_DOUBLE_QUOTES) && str.end_with?(TRIPE_DOUBLE_QUOTES)) ||
    (str.start_with?(TRIPE_SINGLE_QUOTES) && str.end_with?(TRIPE_SINGLE_QUOTES)))
    str = str.byteslice(3..-4)
  else
    str = str.byteslice(1..-2)
  end

  cleanup_escape_sequences(str)
end

def convert_to_bytes(str)
  str.unpack("C*")
end


BIN_ESCAPE = /\\([0-3][0-7][0-7])/
HEX_ESCAPE = /\\x([0-9a-fA-F]{2})/
BPM_ESCAPE = /\\u([0-9a-fA-F]{4})/
UNICODE_ESCAPE = /\\u([0-9a-fA-F]{4})/
WHITESPACE_ESCAPE = /\\([bfnrt"'\\])/
ESCAPE_UNION = Regexp.union(BIN_ESCAPE, HEX_ESCAPE, BPM_ESCAPE, WHITESPACE_ESCAPE)
# For the sake of a readable representation, the escape sequences (ESCAPE) are kept
# implicit in string tokens. This means that strings without the r or R (raw) prefix
# process ESCAPE sequences, while in strings with the raw prefix they stay uninterpreted.
# See documentation of string literals below.
def cleanup_escape_sequences(str)
  str.gsub!(ESCAPE_UNION) do |match|
    case match
    when BIN_ESCAPE
      # For strings, it denotes the unicode code point.
      Regexp.last_match(1).to_i.chr(Encoding::UTF_8)
    when HEX_ESCAPE
      # For strings, it denotes the unicode code point.
      Regexp.last_match(1).hex.chr(Encoding::UTF_8)
    when BPM_ESCAPE
      Regexp.last_match(1).hex.chr(Encoding::BPM)
    when UNICODE_ESCAPE
      # encoding a Unicode code point. Valid only for string literals.
      Regexp.last_match(1).hex.chr(Encoding::UTF_8)
    when WHITESPACE_ESCAPE
      Regexp.last_match(0)
    end
  end
  str
end

...end parser.ry/module_eval...
##### State transition tables begin ###

racc_action_table = [
     9,    10,     7,     8,     6,    18,     4,     3,    12,     5,
     9,    10,     7,     8,     4,     3,    13,     5,     4,     3,
   nil,     5,     4,     3,   nil,     5,     4,     3,   nil,     5,
     4,     3,   nil,     5,     9,    10,     9,    10 ]

racc_action_check = [
    11,    11,    11,    11,     1,    11,     0,     0,     4,     0,
     2,     2,     2,     2,     3,     3,     6,     3,     7,     7,
   nil,     7,     8,     8,   nil,     8,     9,     9,   nil,     9,
    10,    10,   nil,    10,    14,    14,    15,    15 ]

racc_action_pointer = [
     0,     4,     7,     8,    -1,   nil,    16,    12,    16,    20,
    24,    -3,   nil,   nil,    31,    33,   nil,   nil,   nil ]

racc_action_default = [
    -2,   -10,    -1,   -10,   -10,    -9,   -10,   -10,   -10,   -10,
   -10,   -10,    -8,    19,    -3,    -4,    -5,    -6,    -7 ]

racc_goto_table = [
     2,     1,   nil,    11,   nil,   nil,   nil,    14,    15,    16,
    17 ]

racc_goto_check = [
     2,     1,   nil,     2,   nil,   nil,   nil,     2,     2,     2,
     2 ]

racc_goto_pointer = [
   nil,     1,     0 ]

racc_goto_default = [
   nil,   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 11, :_reduce_none,
  0, 11, :_reduce_2,
  3, 12, :_reduce_3,
  3, 12, :_reduce_4,
  3, 12, :_reduce_5,
  3, 12, :_reduce_6,
  3, 12, :_reduce_7,
  2, 12, :_reduce_8,
  1, 12, :_reduce_none ]

racc_reduce_n = 10

racc_shift_n = 19

racc_token_table = {
  false => 0,
  :error => 1,
  :UMINUS => 2,
  "*" => 3,
  "/" => 4,
  "+" => 5,
  "-" => 6,
  "(" => 7,
  ")" => 8,
  :NUMBER => 9 }

racc_nt_base = 10

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "UMINUS",
  "\"*\"",
  "\"/\"",
  "\"+\"",
  "\"-\"",
  "\"(\"",
  "\")\"",
  "NUMBER",
  "$start",
  "target",
  "exp" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

module_eval(<<'.,.,', 'parser.ry', 9)
  def _reduce_2(val, _values, result)
     result = 0
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.ry', 11)
  def _reduce_3(val, _values, result)
     result += val[2]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.ry', 12)
  def _reduce_4(val, _values, result)
     result -= val[2]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.ry', 13)
  def _reduce_5(val, _values, result)
     result *= val[2]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.ry', 14)
  def _reduce_6(val, _values, result)
     result /= val[2]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.ry', 15)
  def _reduce_7(val, _values, result)
     result = val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.ry', 16)
  def _reduce_8(val, _values, result)
     result = -val[1]
    result
  end
.,.,

# reduce 9 omitted

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Parser
end   # module Cel


if $0 == __FILE__
  examples = <<EOS
123
12345
1.2
1e2
-1.2e2
12u
0xa123
""
'""'
'''x''x'''
"\""
"\\"
r"\\"
b"abc"
b"ÿ"
b"\303\277"
"\303\277"
"\377"
b"\377"
"\xFF"
b"\xFF"

1 + 2
3 - 2
" Some String with \"escapes\""
'another string'
a.b.c == 1
d > 2
a.b.c * 3 == 1 && d > 2
a.b.c
wiri
// a.driving_license = "CA"
// 1 = 2
// 2 = "a"
// a.b.c > "a"
EOS
  puts 'Parsing...'
  parser = Cel::Parser.new
  examples.each_line do |line|
    puts "line: #{line.inspect}"
    puts parser.parse(line)
  end
end

# Expr           = ConditionalOr ["?" ConditionalOr ":" Expr] ;
# ConditionalOr  = [ConditionalOr "||"] ConditionalAnd ;
# ConditionalAnd = [ConditionalAnd "&&"] Relation ;
# Relation       = [Relation Relop] Addition ;
# Relop          = "<" | "<=" | ">=" | ">" | "==" | "!=" | "in" ;
# Addition       = [Addition ("+" | "-")] Multiplication ;
# Multiplication = [Multiplication ("*" | "/" | "%")] Unary ;
# Unary          = Member
#                | "!" {"!"} Member
#                | "-" {"-"} Member
#                ;
# Member         = Primary
#                | Member "." IDENT ["(" [ExprList] ")"]
#                | Member "[" Expr "]"
#                | Member "{" [FieldInits] "}"
#                ;
# Primary        = ["."] IDENT ["(" [ExprList] ")"]
#                | "(" Expr ")"
#                | "[" [ExprList] "]"
#                | "{" [MapInits] "}"
#                | LITERAL
#                ;
# ExprList       = Expr {"," Expr} ;
# FieldInits     = IDENT ":" Expr {"," IDENT ":" Expr} ;
# MapInits       = Expr ":" Expr {"," Expr ":" Expr} ;

# IDENT          ::= [_a-zA-Z][_a-zA-Z0-9]* - RESERVED
# LITERAL        ::= INT_LIT | UINT_LIT | FLOAT_LIT | STRING_LIT | BYTES_LIT
# | BOOL_LIT | NULL_LIT
# INT_LIT        ::= -? DIGIT+ | -? 0x HEXDIGIT+
# UINT_LIT       ::= INT_LIT [uU]
# FLOAT_LIT      ::= -? DIGIT* . DIGIT+ EXPONENT? | -? DIGIT+ EXPONENT
# DIGIT          ::= [0-9]
# HEXDIGIT       ::= [0-9abcdefABCDEF]
# EXPONENT       ::= [eE] [+-]? DIGIT+
# STRING_LIT     ::= [rR]? ( "    ~( " | NEWLINE )*  "
#         | '    ~( ' | NEWLINE )*  '
#         | """  ~"""*              """
#         | '''  ~'''*              '''
#         )
# BYTES_LIT      ::= [bB] STRING_LIT
# ESCAPE         ::= \ [bfnrt"'\]
# | \ x HEXDIGIT HEXDIGIT
# | \ u HEXDIGIT HEXDIGIT HEXDIGIT HEXDIGIT
# | \ U HEXDIGIT HEXDIGIT HEXDIGIT HEXDIGIT HEXDIGIT HEXDIGIT HEXDIGIT HEXDIGIT
# | \ [0-3] [0-7] [0-7]
# NEWLINE        ::= \r\n | \r | \n
# BOOL_LIT       ::= "true" | "false"
# NULL_LIT       ::= "null"
# RESERVED       ::= BOOL_LIT | NULL_LIT | "in"
# | "as" | "break" | "const" | "continue" | "else"
# | "for" | "function" | "if" | "import" | "let"
# | "loop" | "package" | "namespace" | "return"
# | "var" | "void" | "while"
# WHITESPACE     ::= [\t\n\f\r ]+
# COMMENT        ::= '//' ~NEWLINE* NEWLINE
