TargetRubyVersion: 2.7
parallel: true          # default: false
format: progress        # default: Standard::Formatter
default_ignores: false  # default: true
ignore:                 # default: []
  - 'lib/cel/parser.rb'
  - 'vendor/**/*'
  - '**/*':
    - Style/SafeNavigation