# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cel/expr/explain.proto

require 'google/protobuf'

require 'cel/expr/value_pb'


descriptor_data = "\n\x16\x63\x65l/expr/explain.proto\x12\x08\x63\x65l.expr\x1a\x14\x63\x65l/expr/value.proto\"\x8b\x01\n\x07\x45xplain\x12\x1f\n\x06values\x18\x01 \x03(\x0b\x32\x0f.cel.expr.Value\x12.\n\nexpr_steps\x18\x02 \x03(\x0b\x32\x1a.cel.expr.Explain.ExprStep\x1a+\n\x08\x45xprStep\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x13\n\x0bvalue_index\x18\x02 \x01(\x05:\x02\x18\x01\x42/\n\x0c\x64\x65v.cel.exprB\x0c\x45xplainProtoP\x01Z\x0c\x63\x65l.dev/expr\xf8\x01\x01\x62\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Cel
  module Expr
    Explain = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cel.expr.Explain").msgclass
    Explain::ExprStep = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cel.expr.Explain.ExprStep").msgclass
  end
end
