# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cel/expr/value.proto

require 'google/protobuf'

require 'google/protobuf/any_pb'
require 'google/protobuf/struct_pb'


descriptor_data = "\n\x14\x63\x65l/expr/value.proto\x12\x08\x63\x65l.expr\x1a\x19google/protobuf/any.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x90\x03\n\x05Value\x12\x30\n\nnull_value\x18\x01 \x01(\x0e\x32\x1a.google.protobuf.NullValueH\x00\x12\x14\n\nbool_value\x18\x02 \x01(\x08H\x00\x12\x15\n\x0bint64_value\x18\x03 \x01(\x03H\x00\x12\x16\n\x0cuint64_value\x18\x04 \x01(\x04H\x00\x12\x16\n\x0c\x64ouble_value\x18\x05 \x01(\x01H\x00\x12\x16\n\x0cstring_value\x18\x06 \x01(\tH\x00\x12\x15\n\x0b\x62ytes_value\x18\x07 \x01(\x0cH\x00\x12)\n\nenum_value\x18\t \x01(\x0b\x32\x13.cel.expr.EnumValueH\x00\x12,\n\x0cobject_value\x18\n \x01(\x0b\x32\x14.google.protobuf.AnyH\x00\x12\'\n\tmap_value\x18\x0b \x01(\x0b\x32\x12.cel.expr.MapValueH\x00\x12)\n\nlist_value\x18\x0c \x01(\x0b\x32\x13.cel.expr.ListValueH\x00\x12\x14\n\ntype_value\x18\x0f \x01(\tH\x00\x42\x06\n\x04kind\"(\n\tEnumValue\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05\",\n\tListValue\x12\x1f\n\x06values\x18\x01 \x03(\x0b\x32\x0f.cel.expr.Value\"|\n\x08MapValue\x12)\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x18.cel.expr.MapValue.Entry\x1a\x45\n\x05\x45ntry\x12\x1c\n\x03key\x18\x01 \x01(\x0b\x32\x0f.cel.expr.Value\x12\x1e\n\x05value\x18\x02 \x01(\x0b\x32\x0f.cel.expr.ValueB-\n\x0c\x64\x65v.cel.exprB\nValueProtoP\x01Z\x0c\x63\x65l.dev/expr\xf8\x01\x01\x62\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Cel
  module Expr
    Value = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cel.expr.Value").msgclass
    EnumValue = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cel.expr.EnumValue").msgclass
    ListValue = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cel.expr.ListValue").msgclass
    MapValue = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cel.expr.MapValue").msgclass
    MapValue::Entry = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cel.expr.MapValue.Entry").msgclass
  end
end
