# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cel/expr/conformance/proto2/test_all_types_extensions.proto

require 'google/protobuf'

require 'cel/expr/conformance/proto2/test_all_types_pb'


descriptor_data = "\n;cel/expr/conformance/proto2/test_all_types_extensions.proto\x12\x1b\x63\x65l.expr.conformance.proto2\x1a\x30\x63\x65l/expr/conformance/proto2/test_all_types.proto\"\xda\x03\n\x1cProto2ExtensionScopedMessage2=\n\tint64_ext\x12).cel.expr.conformance.proto2.TestAllTypes\x18\xed\x07 \x01(\x03\x32x\n\x19message_scoped_nested_ext\x12).cel.expr.conformance.proto2.TestAllTypes\x18\xee\x07 \x01(\x0b\x32).cel.expr.conformance.proto2.TestAllTypes2y\n\x0fnested_enum_ext\x12).cel.expr.conformance.proto2.TestAllTypes\x18\xef\x07 \x01(\x0e\x32\x34.cel.expr.conformance.proto2.TestAllTypes.NestedEnum2\x85\x01\n&message_scoped_repeated_test_all_types\x12).cel.expr.conformance.proto2.TestAllTypes\x18\xf0\x07 \x03(\x0b\x32).cel.expr.conformance.proto2.TestAllTypes:=\n\tint32_ext\x12).cel.expr.conformance.proto2.TestAllTypes\x18\xe8\x07 \x01(\x05:i\n\nnested_ext\x12).cel.expr.conformance.proto2.TestAllTypes\x18\xe9\x07 \x01(\x0b\x32).cel.expr.conformance.proto2.TestAllTypes:q\n\x12test_all_types_ext\x12).cel.expr.conformance.proto2.TestAllTypes\x18\xea\x07 \x01(\x0b\x32).cel.expr.conformance.proto2.TestAllTypes:y\n\x0fnested_enum_ext\x12).cel.expr.conformance.proto2.TestAllTypes\x18\xeb\x07 \x01(\x0e\x32\x34.cel.expr.conformance.proto2.TestAllTypes.NestedEnum:v\n\x17repeated_test_all_types\x12).cel.expr.conformance.proto2.TestAllTypes\x18\xec\x07 \x03(\x0b\x32).cel.expr.conformance.proto2.TestAllTypesB_\n\x1f\x64\x65v.cel.expr.conformance.proto2B\x16TestAllTypesExtensionsP\x01Z\x1f\x63\x65l.dev/expr/conformance/proto2\xf8\x01\x01"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Cel
  module Expr
    module Conformance
      module Proto2
        Proto2ExtensionScopedMessage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("cel.expr.conformance.proto2.Proto2ExtensionScopedMessage").msgclass
      end
    end
  end
end
