name: Build and Test
on: [push]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby: ['2.7', '3.4', jruby, truffleruby]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run tests
      run: bundle exec rake test
    - name: Rubocop
      run: bundle exec rake rubocop
  conformance:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4'
        bundler-cache: true
    - name: Run conformance suite
      run: bundle exec rake conformance
